% Function to create the monitor dependant on the number of layers
function monitor = generate_monitor(is_visible)
% Create the training progress monitor with the appropriate configuration
monitor = trainingProgressMonitor( ...
    Metrics=["TrainingRMSE", "ValidationRMSE", "TrainingRMSE_smooth"], ...
    Info=["LearnRate", "Epoch", "Iteration", "ExecutionEnvironment"], ...
    XLabel="Iteration", ...
    Visible=is_visible);

groupSubPlot(monitor, "RMSE", ["TrainingRMSE", "TrainingRMSE_smooth", "ValidationRMSE"]);
end